title:
  2: Bottleneck
  1: Goulot d'etranglement
testIn: |-
  5 2 40
  5 10 1000
  20 20
  3 6
  ####################
  #######.############
  #####...############
  ####....############
  ###.....############
  ##.......#####...###
  ##.......####.....##
  #..................#
  #..................#
  #..................#
  #..............XX..#
  #.......#####..XX..#
  #......######......#
  #......######.....##
  ##.....#######...###
  ##.....#############
  ###....#############
  ####...#############
  #####.##############
  ####################
isTest: 'true'
isValidator: 'true'