title:
  2: Sweet home
  1: Doux foyer
testIn: |-
  3 2 100
  2 2 3700
  10 10
  3 3
  ##########
  #........#
  #........#
  #........#
  #........#
  #.....X..#
  #........#
  #........#
  #........#
  ##########
isTest: 'true'
isValidator: 'true'