title:
  2: Big map with villages and wall
  1: Grand terrain avec villages et mur
testIn: |-
  3 2 1
  5 3 60
  50 40
  13 16
  ##################################################
  #################..............###################
  ###########........................###############
  ##########............................############
  #########...............XXXXXXX.........##########
  #######...............XXXXXXXXXX........##########
  ######................XXXXXXXXXX.........#########
  #####.................XXXXXXXXXX.........#########
  ####..................XXXXXXXXXX.........#########
  ###....................XXXXXXXX..........#########
  ##.......................................#########
  ##.........................................#######
  ##..........................................######
  #............................................#####
  #.............................................####
  #.............................................####
  ##.............................................###
  ####...........................................###
  #######........................................###
  ###############................................###
  ####################...........................###
  ########............####.......................###
  ####....................####...................###
  ##..........................###................###
  #..............................................###
  #..............................................###
  #.............................................####
  #.............................................####
  ##...............................XXXXXXX......####
  ##.....XXXXXX...................XXXXXXXXX.....####
  ##....XXXXXXXXX.................XXXXXXXXX.....####
  ###...XXXXXXXXX.................XXXXXXXXX....#####
  ####..XXXXXXXXX.................XXXXXXXXX....#####
  #####..XXXXXXX...................XXXXXXX....######
  #####.......................................######
  ######.....................................#######
  ########...................................#######
  #########.................................########
  ###########..............................#########
  ##################################################
isTest: 'true'
isValidator: 'true'