title:
  2: Big homogeneous map
  1: Grand terrain homogene
testIn: |-
  1 2 5
  0 0 0
  49 49
  24 24
  #################################################
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #################################################
isTest: 'true'
isValidator: 'true'