title:
  2: Big random map
  1: Grand terrain aleatoire
testIn: |-
  3 2 1
  5 3 100
  49 49
  24 24
  #################################################
  #...X.#....#.....#..#...X..#..X..#...#....###.#.#
  ##..#.X#...#..#.##......##.#.##.....##......#...#
  #....####.....#....X...#..#............#....#...#
  #.###..#..........#................##.###.X#....#
  #.#..#....##.##...#....##..X....X.X...###.X...#.#
  #.##...#......#........X...#.........#.X#.......#
  #X..##..#.......#.#..##..###..###......#......#.#
  #.#....##..X...###.....###...####..#.......##..X#
  #.#...#......#.###..X..#...X###..X....#..#.....X#
  #...........#...#....#......#...#...#.###.......#
  #.....#.#....#............#..##......#.#..##....#
  ##.#....X.#.#........#X.##...#.X..#.....##...#.##
  ##..#..#.....#.#...#.##X.#..##.X#..X.#.##..#....#
  #..##...X............#.####..#...........#....#.#
  #..###.......##...........#......###..#.#XX#.#..#
  #X.##.###......#.X...###X####.##.....#.X#.......#
  #..##.#...###..#....X.#.#.#...#.#...X.#...#..#..#
  #............#....#...#.................#.......#
  ##.#................#.#..X............#.####...X#
  #.....#...................#......#.#.......X.####
  #......#.#.......X#...#........#..#..X.....#....#
  ##.....#..#.#.#.#............#X##.....#.........#
  #......#..........###X.........#..#....##...#.#.#
  #....#..#.##.#...#.#.X.X.#.....#..##.#......#...#
  #..#.X..#....#.....#.....X#..#......#.....#...#.#
  ###......#..X##.#.........#...#...####.#..#.#.#.#
  #.....#.....##.#.....##....#..##..###...#.#.....#
  #.....##.#.....##.##.#......X#............#...#.#
  #....##..#......#.....#...........#...X.........#
  #...X#......#....###...#.##...........#..X##....#
  ##.....#........#......X.#.....#..#.##.......#..#
  ##.......##.................#.##X...........X.#.#
  ##.....##.#..X......#..#.#........#........#...##
  ##.....##..#.....#.#.#.#...#........##.........##
  #..X....#..##..###X..##....##..#..#X.##.#.#..X..#
  #......X...#...#.#...#.##....#..###.X....#...####
  #...X........#...X#......#...#.......#...#...X..#
  #.....#.......#X....##.....##...#.....#.##..##..#
  #.X#.#.......#.......####...#.#.##.#..X..#.#....#
  #.#...........#.#.#X.#.##..#.#..#..#.....#..##..#
  ##...##.#.....#...#..#..#.#.X.#....X......#.#...#
  ###....##....#.X....#...X......#...##...........#
  #..#..##..#.......#...#.X#...X...######XX.#.#.#.#
  #..#.....#..##....#.....#X##......##............#
  #X#.......X###....#...##.....#.....#..X..#X#....#
  #............#.#........#X.........#X...#..#....#
  #..#..........#......#...#...##......#...X.#...X#
  #################################################
isTest: 'true'
isValidator: 'true'