title:
  2: Big map
  1: Grand terrain
testIn: |-
  100
  2 3 1
  2 5 100
  50 40
  13 22
  ##################################################
  #################..............###################
  ###########........................###############
  ##########............................############
  #########..............XXXXXXXX.........##########
  #######...............XXXXXXXXXX........##########
  ######................XXXXXXXXXX.........#########
  #####.................XXXXXXXXXX.........#########
  ####..................XXXXXXXXXX.........#########
  ###....................XXXXXXXX..........#########
  ##.......................................#########
  ##.........................................#######
  ##..........................................######
  #............................................#####
  #.............................................####
  #.............................................####
  #..............................................###
  #..............................................###
  ####...........................................###
  #..##..........................................###
  #....##........................................###
  #.....###......................................###
  #.......##.....................................###
  #........###...................................###
  #..........##..................................###
  #...........##.................................###
  #.............##..............................####
  #..............##.............................####
  ##..............##...............XXXXXXX......####
  ##.....XXXXXXX....##............XXXXXXXXX.....####
  ##....XXXXXXXXX....##...........XXXXXXXXX.....####
  ###...XXXXXXXXX.....#...........XXXXXXXXX....#####
  ####..XXXXXXXXX......#..........XXXXXXXXX....#####
  #####..XXXXXXX.......##..........XXXXXXX....######
  #####.................#.....................######
  ######................#....................#######
  ########...............#...................#######
  #########..............#..................########
  ###########............##................#########
  ##################################################
isTest: 'true'
isValidator: 'true'