title:
  2: Double intervention
  1: Double intervention
testIn: |-
  7 2 40
  7 10 1000
  20 20
  3 6
  ####################
  #######.############
  #####...############
  ####....############
  ###.....############
  ##.......#####...###
  ##................##
  #..................#
  #........#######...#
  #..................#
  #..............XX..#
  #.......###....XX..#
  #......######......#
  #......######.....##
  ##.....#######...###
  ##.....#############
  ###....#############
  ####...#############
  #####..#############
  ####################
isTest: 'true'
isValidator: 'true'