title:
  2: No sooner said than done
  1: Aussitot dit aussitot fait
testIn: |-
  2 10 100
  2 10 3700
  10 10
  3 3
  ##########
  #........#
  #........#
  #........#
  #........#
  #.....X..#
  #........#
  #........#
  #........#
  ##########
isTest: 'true'
isValidator: 'true'