title:
  2: Homogeneous
  1: Homogene
testIn: |-
  1200
  1 2 1
  0 0 0
  49 49
  24 24
  #################################################
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #...............................................#
  #################################################
isTest: 'true'
isValidator: 'true'